export const LinkTo = {
  root: '/',
  dashboard: '/app',
  home: '/home',
  tours: '/tours',
  createtour: '/tours/create',
  sales: '/sales',
  clients: '/clients',
  mail: '/mail',
  toursCreate: '/tours/create',
  toursEdit: '/tours/edit',
  forgetPassword: '/forget-password',
  login: '/login',
  sigunp: '/signup',
  logout: '/logout',
}
