export const dashboardLinks = {
  root: '/',
  dashboard: '/app',
  home: '/home',
  tours: '/tours',
  createtour: '/tours/create',
  sales: '/sales',
  clients: '/clients',
  mail: '/mail',
  toursCreate: '/tours/create',
  toursEdit: '/tours/edit',
  forgetPassword: '/forget-password',
}
export const mainLinks = {
  homeRoot: '/',
  home: '/home',
  login: '/login',
  sigunp: '/signup',
  logout: '/logout',
  browse: '/browse',
  search: '/search',
  borwse: '/borwse',
  wishlist: '/wishlist',
  about: '/about',
  privacy: '/privacy',
  terms: '/terms',
}
